version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ardhi
      POSTGRES_PASSWORD: ardhi@26
      POSTGRES_DB: tes-soal-online
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: